[package]
name = "surveilr_extensions"
version = "0.1.0"
edition = "2021"

[dependencies]
libsqlite3-sys = { version = "0.30.1", features = ["bundled"]}

[build-dependencies]
cc = "1.0"

[dev-dependencies]
rusqlite = "0.32.1"